name: Deploy App

on:
  push:
    branches:
      - main
      
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20'

        - name: Install dependencies
          run: npm install

        - name: Build React App
          run: npm run build

        - name: Deploy to DO Server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.PRIVATE_KEY }}
            script: |
             cd ${{ secrets.DEPLOY_PATH }}
             git pull origin main
             npm install
             npm run build
             sudo service nginx restart